#include "PluginEditor.h"
#include "BinaryData.h"   // generated by juce_add_binary_data (SILAWebUI)

SilaAudioProcessorEditor::SilaAudioProcessorEditor (SilaAudioProcessor& p)
    : juce::AudioProcessorEditor (&p), processor (p)
{
    addAndMakeVisible (webView);
    setResizable (true, true);
    setSize (1100, 720);

    // Load the bundled UI; the resource provider serves index.html etc.
    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
}

void SilaAudioProcessorEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

std::optional<juce::WebBrowserComponent::Resource>
SilaAudioProcessorEditor::serveResource (const juce::String& url)
{
    // Map "/" → index.html, otherwise strip leading '/'.
    const auto path = (url == "/") ? juce::String ("index.html") : url.fromFirstOccurrenceOf ("/", false, false);

    auto give = [] (const char* data, int size, juce::String mime)
        -> juce::WebBrowserComponent::Resource
    {
        std::vector<std::byte> bytes (static_cast<size_t> (size));
        std::memcpy (bytes.data(), data, static_cast<size_t> (size));
        return { std::move (bytes), std::move (mime) };
    };

    int size = 0;
    if (path == "index.html")
        if (auto* d = BinaryData::getNamedResource ("index_html", size))
            return give (d, size, "text/html");
    if (path == "app.js")
        if (auto* d = BinaryData::getNamedResource ("app_js", size))
            return give (d, size, "text/javascript");
    if (path == "bridge.js")
        if (auto* d = BinaryData::getNamedResource ("bridge_js", size))
            return give (d, size, "text/javascript");

    return std::nullopt;
}

juce::var SilaAudioProcessorEditor::handleBackendCall (
    const juce::Array<juce::var>& args,
    juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    // args = [method, path, body] — the same shape as the old REST api().
    // TODO: route to the engine, e.g.:
    //   "POST" "/tracks"            → processor add track  → return TrackModel json
    //   "PUT"  "/tracks/{id}/steps" → processor toggle step
    //   "POST" "/sequencer/start"   → (no-op: transport is the host's)
    // For now, acknowledge so the UI keeps working during bring-up.
    juce::ignoreUnused (args);
    completion (juce::var (new juce::DynamicObject()));
    return {};
}
