#include "PluginEditor.h"
#include "BinaryData.h"   // generated by juce_add_binary_data (SILAWebUI)
#include "engine/DigitaktExport.h"
#include "engine/ProjectJson.h"
#include <cstring>

using namespace sila::engine;

namespace
{
// All Project<->var helpers now live in engine/ProjectJson.{h,cpp} (one source
// of truth shared with the processor's DAW state). `using namespace sila::engine`
// (above) resolves stepToVar/applyStepVar/trackToVar/parseSampleLayers here.
//
// GET /project payload = the shared structural Project + the UI-only performance
// scalars (swing/songMode/bpm are APVTS params, not part of the Project).
juce::var projectToVar (const Project& p, float swing, bool songMode, double bpm)
{
    juce::var v = sila::engine::projectToVar (p);
    if (auto* o = v.getDynamicObject())
    {
        o->setProperty ("name",      juce::String ("SILA"));
        o->setProperty ("bpm",       bpm);
        o->setProperty ("swing",     (double) swing);
        o->setProperty ("song_mode", songMode);
    }
    return v;
}

juce::var emptyObject() { return juce::var (new juce::DynamicObject()); }

// Filter-mode <-> AudioParameterChoice index (0=LP, 1=HP, 2=BP).
const char* fmodeName  (int idx)               { return idx == 1 ? "highpass" : idx == 2 ? "bandpass" : "lowpass"; }
int         fmodeIndex (const juce::String& s) { return s == "highpass" ? 1 : s == "bandpass" ? 2 : 0; }

bool isAudioFile (const juce::File& f)
{
    const auto ext = f.getFileExtension().toLowerCase();
    return ext == ".wav" || ext == ".aiff" || ext == ".aif";
}

// Port of library/browser.py::get_library_tree — a two-level pack/category/
// sample tree from ~/SILA/library. "My Samples" pinned first, then packs
// alphabetically; empty categories omitted. Built on the message thread.
juce::var libraryTreeVar (const juce::File& root)
{
    auto* result = new juce::DynamicObject();
    juce::Array<juce::var> packs;
    if (! root.isDirectory())
    {
        result->setProperty ("packs", packs);
        return juce::var (result);
    }

    auto byName = [] (const juce::File& a, const juce::File& b)
                     { return a.getFileName().compareNatural (b.getFileName()) < 0; };

    auto packDirs = root.findChildFiles (juce::File::findDirectories | juce::File::ignoreHiddenFiles, false);
    std::sort (packDirs.begin(), packDirs.end(), byName);

    // Pin "My Samples" at the top regardless of alphabetical order.
    const juce::String kMySamples = "My Samples";
    juce::Array<juce::File> ordered;
    for (const auto& d : packDirs) if (d.getFileName() == kMySamples) ordered.add (d);
    for (const auto& d : packDirs) if (d.getFileName() != kMySamples) ordered.add (d);

    for (const auto& packDir : ordered)
    {
        auto* pack = new juce::DynamicObject();
        pack->setProperty ("name", packDir.getFileName());
        pack->setProperty ("path", packDir.getFileName());
        juce::Array<juce::var> categories;

        auto catDirs = packDir.findChildFiles (juce::File::findDirectories | juce::File::ignoreHiddenFiles, false);
        std::sort (catDirs.begin(), catDirs.end(), byName);
        for (const auto& catDir : catDirs)
        {
            auto files = catDir.findChildFiles (juce::File::findFiles | juce::File::ignoreHiddenFiles, false);
            std::sort (files.begin(), files.end(), byName);

            juce::Array<juce::var> samples;
            for (const auto& f : files)
            {
                if (! isAudioFile (f)) continue;
                auto* s = new juce::DynamicObject();
                s->setProperty ("name",     f.getFileNameWithoutExtension());
                s->setProperty ("filename", f.getFileName());
                s->setProperty ("path",     packDir.getFileName() + "/" + catDir.getFileName() + "/" + f.getFileName());
                s->setProperty ("size_bytes", (juce::int64) f.getSize());
                samples.add (juce::var (s));
            }
            if (samples.isEmpty()) continue;   // omit empty categories

            auto* cat = new juce::DynamicObject();
            cat->setProperty ("name",    catDir.getFileName());
            cat->setProperty ("path",    packDir.getFileName() + "/" + catDir.getFileName());
            cat->setProperty ("samples", samples);
            categories.add (juce::var (cat));
        }
        pack->setProperty ("categories", categories);
        packs.add (juce::var (pack));
    }

    result->setProperty ("packs", packs);
    return juce::var (result);
}

// Transport status payload — port of /sequencer/status. The plugin has no
// server clock to fail, so healthy is always true and error/startup_warning are
// null; current_song_slot is null (not -1) when song mode is off/stopped, to
// match the Python contract the UI already speaks.
juce::var statusVar (bool playing, double bpm, int songSlot, int songRow, int songRepeat)
{
    auto* o = new juce::DynamicObject();
    o->setProperty ("playing", playing);
    o->setProperty ("bpm", bpm);
    o->setProperty ("healthy", true);
    o->setProperty ("error", juce::var());
    o->setProperty ("startup_warning", juce::var());
    o->setProperty ("current_song_slot", songSlot >= 0 ? juce::var (songSlot) : juce::var());
    // Song-mode playhead (Phase 6): which row is playing + how many repeats in.
    o->setProperty ("current_song_row",    songRow >= 0 ? juce::var (songRow) : juce::var());
    o->setProperty ("current_song_repeat", songRepeat);
    return juce::var (o);
}
}

SilaAudioProcessorEditor::SilaAudioProcessorEditor (SilaAudioProcessor& p)
    : juce::AudioProcessorEditor (&p),
      processor (p),
      webView (juce::WebBrowserComponent::Options{}
                   .withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
                   .withWinWebView2Options (juce::WebBrowserComponent::Options::WinWebView2{}
                       .withUserDataFolder (juce::File::getSpecialLocation (juce::File::tempDirectory)))
                   .withNativeIntegrationEnabled()
                   .withOptionsFrom (songModeRelay)
                   .withNativeFunction ("backendCall",
                       [this] (const juce::Array<juce::var>& args,
                               juce::WebBrowserComponent::NativeFunctionCompletion completion)
                       {
                           completion (handleBackendCall (args));
                       })
                   .withResourceProvider ([this] (const juce::String& url) { return serveResource (url); })),
      songModeAttachment (*p.apvts.getParameter ("songMode"), songModeRelay, p.apvts.undoManager)
{
    addAndMakeVisible (webView);
    setResizable (true, true);
    setSize (980, 460);

    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Seed from the current epoch so a state load applied before the UI opened
    // (host restores state, then shows the editor) doesn't trigger a redundant
    // reload — boot()'s GET /project already reads that snapshot.
    lastSeenEpoch = processor.projectEpoch.load (std::memory_order_acquire);

    startTimerHz (30);   // playhead push + status + project-epoch + snapshot reclaim
}

SilaAudioProcessorEditor::~SilaAudioProcessorEditor()
{
    stopTimer();
}

void SilaAudioProcessorEditor::paint (juce::Graphics& g)
{
    g.fillAll (juce::Colour (0xff0a0e14));
}

void SilaAudioProcessorEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

float SilaAudioProcessorEditor::currentSwing() const
{
    const auto* pv = processor.apvts.getRawParameterValue ("swing");
    return pv != nullptr ? pv->load() : 0.0f;
}

bool SilaAudioProcessorEditor::currentSongMode() const
{
    const auto* pv = processor.apvts.getRawParameterValue ("songMode");
    return pv != nullptr && pv->load() > 0.5f;
}

int SilaAudioProcessorEditor::trackSlot (const juce::String& id) const
{
    if (auto snap = processor.snapshot())
        for (int i = 0; i < (int) snap->tracks.size(); ++i)
            if (snap->tracks[(size_t) i].id == id)
                return i;
    return -1;
}

float SilaAudioProcessorEditor::slotValue (int slot, const juce::String& pid) const
{
    const auto* a = processor.apvts.getRawParameterValue ("t" + juce::String (slot) + "_" + pid);
    return a != nullptr ? a->load() : 0.0f;
}

void SilaAudioProcessorEditor::setSlotValue (int slot, const juce::String& pid, float value)
{
    if (auto* p = processor.apvts.getParameter ("t" + juce::String (slot) + "_" + pid))
        p->setValueNotifyingHost (p->convertTo0to1 (value));
}

void SilaAudioProcessorEditor::timerCallback()
{
    // Reclaim snapshots the audio thread has finished with (message thread).
    processor.reapRetired();

    // Push the latest transport position to the UI when it changed.
    const double ppq = processor.currentPpq.load (std::memory_order_relaxed);
    if (ppq != lastSentPpq)
    {
        lastSentPpq = ppq;
        webView.emitEventIfBrowserIsVisible ("playhead", juce::var (ppq));
    }

    // Push transport status only on change (replaces the Python app's 2 s poll).
    const bool   playing = processor.transportPlaying.load (std::memory_order_relaxed);
    const double bpm     = processor.currentBpm.load (std::memory_order_relaxed);
    const int    slot    = processor.currentSongSlot.load (std::memory_order_relaxed);
    const int    row     = processor.currentSongRow.load (std::memory_order_relaxed);
    const int    repeat  = processor.currentSongRepeat.load (std::memory_order_relaxed);
    if (playing != lastSentPlaying || bpm != lastSentBpm || slot != lastSentSongSlot
        || row != lastSentSongRow)
    {
        lastSentPlaying  = playing;
        lastSentBpm      = bpm;
        lastSentSongSlot = slot;
        lastSentSongRow  = row;
        webView.emitEventIfBrowserIsVisible ("status", statusVar (playing, bpm, slot, row, repeat));
    }

    // The processor bumps projectEpoch when DAW state load (setStateInformation)
    // swaps in a whole new Project. Decoupled from the processor: poll it here and
    // tell the UI to re-fetch GET /project rather than holding a listener across
    // threads. Initialised to the live epoch in the ctor, so an already-applied
    // load (UI opened after the host restored state) doesn't double-fetch.
    const uint32_t epoch = processor.projectEpoch.load (std::memory_order_acquire);
    if (epoch != lastSeenEpoch)
    {
        lastSeenEpoch = epoch;
        webView.emitEventIfBrowserIsVisible ("project", juce::var());
    }

    // Push per-slot vol/pan to the UI when they change (host automation / generic
    // editor moved a param). Only the migrated params for now.
    if (auto snap = processor.snapshot())
    {
        juce::Array<juce::var> changed;
        const int n = juce::jmin ((int) snap->tracks.size(), SilaAudioProcessor::kMaxTracks);
        for (int i = 0; i < n; ++i)
        {
            const float vol = slotValue (i, "vol");
            const float pan = slotValue (i, "pan");
            const float cut = slotValue (i, "cutoff");
            const float res = slotValue (i, "res");
            const float fm  = slotValue (i, "fmode");
            if (std::abs (vol - lastVol[i]) > 1.0e-4f || std::abs (pan - lastPan[i]) > 1.0e-4f
                || std::abs (cut - lastCutoff[i]) > 1.0e-4f || std::abs (res - lastRes[i]) > 1.0e-4f
                || std::abs (fm - lastFmode[i]) > 1.0e-4f)
            {
                lastVol[i] = vol; lastPan[i] = pan; lastCutoff[i] = cut; lastRes[i] = res; lastFmode[i] = fm;
                auto* o = new juce::DynamicObject();
                o->setProperty ("index",  i);
                o->setProperty ("id",     snap->tracks[(size_t) i].id);
                o->setProperty ("volume", (double) vol);
                o->setProperty ("pan",    (double) pan);
                o->setProperty ("cutoff", (double) cut);
                o->setProperty ("resonance", (double) res);
                o->setProperty ("filter_mode", fmodeName (juce::roundToInt (fm)));
                changed.add (juce::var (o));
            }
        }
        if (! changed.isEmpty())
            webView.emitEventIfBrowserIsVisible ("params", juce::var (changed));
    }
}

juce::var SilaAudioProcessorEditor::handleBackendCall (const juce::Array<juce::var>& args)
{
    const juce::String method  = args.size() > 0 ? args[0].toString() : juce::String();
    const juce::String rawPath = args.size() > 1 ? args[1].toString() : juce::String();
    const juce::var    body    = args.size() > 2 ? args[2] : juce::var();

    // Split off any ?query so routing/seg-matching see the path only.
    const int qpos           = rawPath.indexOfChar ('?');
    const juce::String path  = qpos >= 0 ? rawPath.substring (0, qpos) : rawPath;
    const juce::String query = qpos >= 0 ? rawPath.substring (qpos + 1) : juce::String();

    juce::StringArray seg;
    seg.addTokens (path, "/", "");
    seg.removeEmptyStrings();   // e.g. ["tracks","Kick","steps","3"]

    // GET /project — serialize the current snapshot for the grid, injecting the
    // per-slot APVTS values (volume/pan) so the UI initialises correctly.
    if (method == "GET" && path == "/project")
        if (auto snap = processor.snapshot())
        {
            juce::var v = projectToVar (*snap, currentSwing(), currentSongMode(),
                                        processor.currentBpm.load (std::memory_order_relaxed));
            // The grid edits one pattern at a time — inject the currentPattern
            // slot's steps as each track's `steps` (blank 16 cells if unauthored).
            const int cp = juce::jlimit (0, PatternBank::kNumSlots - 1, snap->currentPattern);
            const auto& curSlot = snap->patternBank.slots[(size_t) cp];
            if (auto* tracks = v.getProperty ("tracks", juce::var()).getArray())
                for (int i = 0; i < tracks->size() && i < SilaAudioProcessor::kMaxTracks; ++i)
                    if (auto* to = (*tracks)[i].getDynamicObject())
                    {
                        to->setProperty ("volume",     (double) slotValue (i, "vol"));
                        to->setProperty ("pan",        (double) slotValue (i, "pan"));
                        to->setProperty ("cutoff",     (double) slotValue (i, "cutoff"));
                        to->setProperty ("resonance",  (double) slotValue (i, "res"));
                        to->setProperty ("filter_mode", fmodeName (juce::roundToInt (slotValue (i, "fmode"))));

                        juce::Array<juce::var> steps;
                        if (i < (int) curSlot.size() && ! curSlot[(size_t) i].empty())
                            for (const auto& s : curSlot[(size_t) i]) steps.add (stepToVar (s));
                        else   // unauthored / empty column => a blank default-length grid
                            for (int k = 0; k < kDefaultPatternLength; ++k) steps.add (stepToVar (Step{}));
                        to->setProperty ("steps", steps);
                        to->setProperty ("step_count", steps.size());
                    }
            if (auto* vo = v.getDynamicObject())
            {
                // Master pattern length = a non-empty column's size, else default.
                int patternLength = kDefaultPatternLength;
                for (const auto& col : curSlot)
                    if (! col.empty()) { patternLength = (int) col.size(); break; }
                vo->setProperty ("current_pattern", cp);
                vo->setProperty ("pattern_count", PatternBank::kNumSlots);
                vo->setProperty ("pattern_length", patternLength);
                vo->setProperty ("max_pattern_length", kMaxPatternLength);
            }
            return v;
        }

    // POST /tracks { name } — append a track + reset its slot params to defaults.
    if (method == "POST" && path == "/tracks")
    {
        auto snap = processor.snapshot();
        const int newIdx = snap != nullptr ? (int) snap->tracks.size() : 0;
        if (newIdx >= SilaAudioProcessor::kMaxTracks)
        {
            auto* o = new juce::DynamicObject();
            o->setProperty ("error", "max tracks reached");
            return juce::var (o);
        }
        juce::String nm = body.getProperty ("name", juce::String()).toString().trim();
        if (nm.isEmpty()) nm = "Track " + juce::String (newIdx + 1);
        processor.addTrack (nm);
        setSlotValue (newIdx, "vol", 1.0f);  setSlotValue (newIdx, "pan", 0.0f);
        setSlotValue (newIdx, "cutoff", 1.0f); setSlotValue (newIdx, "res", 0.0f);
        setSlotValue (newIdx, "fmode", 0.0f);
        auto* o = new juce::DynamicObject();
        o->setProperty ("added", nm);
        return juce::var (o);
    }

    // DELETE /tracks/{id} — remove a track; shift slot params below it up so the
    // survivors keep their mix/filter settings.
    if (method == "DELETE" && seg.size() == 2 && seg[0] == "tracks")
    {
        const int idx = trackSlot (seg[1]);
        if (idx >= 0)
        {
            auto snap = processor.snapshot();
            const int count = snap != nullptr ? (int) snap->tracks.size() : 0;
            const char* pids[] = { "vol", "pan", "cutoff", "res", "fmode" };
            for (int s = idx; s < count - 1; ++s)
                for (auto* pid : pids)
                    setSlotValue (s, pid, slotValue (s + 1, pid));
            processor.removeTrack (idx);
        }
        return emptyObject();
    }

    // PUT /tracks/{id}/name { name } — rename (snapshot edit; the id stays stable).
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "name")
    {
        const juce::String id = seg[1];
        const juce::String nm = body.getProperty ("name", juce::String()).toString().trim();
        if (nm.isNotEmpty())
            processor.editProject ([&] (Project& proj)
            {
                for (auto& t : proj.tracks) if (t.id == id) { t.name = nm; break; }
            });
        return emptyObject();
    }

    // PUT /tracks/{id}/color { color } — UI accent (hex). Pure metadata; the
    // engine never reads it, so this is just a snapshot edit.
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "color")
    {
        const juce::String id  = seg[1];
        const juce::String col = body.getProperty ("color", juce::String()).toString();
        processor.editProject ([&] (Project& proj)
        {
            for (auto& t : proj.tracks) if (t.id == id) { t.color = col; break; }
        });
        return emptyObject();
    }

    // PUT /tracks/{id}/steps/{idx}  body { step: {...} } — edits the CURRENT
    // pattern slot for this track (materializing the slot on first touch).
    // After removeEmptyStrings the path is ["tracks", id, "steps", idx] (4 segs).
    if (method == "PUT" && seg.size() == 4 && seg[0] == "tracks" && seg[2] == "steps")
    {
        const juce::String id  = seg[1];
        const int          idx = seg[3].getIntValue();
        const juce::var    stepVar = body.getProperty ("step", juce::var());
        processor.editProject ([&] (Project& proj)
        {
            int ti = -1;
            for (int i = 0; i < (int) proj.tracks.size(); ++i)
                if (proj.tracks[(size_t) i].id == id) { ti = i; break; }
            if (ti < 0) return;

            const int cp = juce::jlimit (0, PatternBank::kNumSlots - 1, proj.currentPattern);
            ensurePatternColumns (proj, cp);   // blank slot -> tracks x default length
            auto& col = proj.patternBank.slots[(size_t) cp][(size_t) ti];
            if (idx >= 0 && idx < (int) col.size())
                applyStepVar (col[(size_t) idx], stepVar);
        });
        return emptyObject();
    }

    // PUT /pattern/select { index } — choose which pattern slot the grid edits and
    // pattern mode plays. Structural edit; the UI re-fetches GET /project.
    if (method == "PUT" && path == "/pattern/select")
    {
        const int idx = (int) body.getProperty ("index", 0);
        processor.editProject ([&] (Project& proj)
        {
            proj.currentPattern = juce::jlimit (0, PatternBank::kNumSlots - 1, idx);
        });
        return emptyObject();
    }

    // PUT /pattern/length { length } — set the current pattern's master length
    // (1..128, resizes every track column). The UI re-fetches GET /project.
    if (method == "PUT" && path == "/pattern/length")
    {
        const int len = (int) body.getProperty ("length", kDefaultPatternLength);
        processor.editProject ([&] (Project& proj)
        {
            setPatternLength (proj, proj.currentPattern, len);
        });
        return emptyObject();
    }

    // PUT /tracks/{id}/{volume|pan|cutoff|resonance} — per-track mixer/filter base.
    // volume/pan are APVTS slot params (Phase 6); cutoff/resonance still snapshot.
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks"
        && (seg[2] == "volume" || seg[2] == "pan" || seg[2] == "cutoff" || seg[2] == "resonance"))
    {
        const juce::String id    = seg[1];
        const juce::String which = seg[2];
        const double raw = (double) body.getProperty (which, which == "pan" ? 0.0 : 1.0);
        const int slot = trackSlot (id);
        if (slot >= 0)
        {
            const juce::String pid = which == "volume" ? "vol"
                                   : which == "pan"    ? "pan"
                                   : which == "cutoff" ? "cutoff" : "res";
            const double lo = which == "pan" ? -1.0 : 0.0;
            setSlotValue (slot, pid, (float) juce::jlimit (lo, 1.0, raw));
        }
        return emptyObject();
    }

    // PUT /tracks/{id}/filter_mode { mode: lowpass|highpass|bandpass } — fmode is
    // an AudioParameterChoice in the slot bank (index 0/1/2).
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "filter_mode")
    {
        const int slot = trackSlot (seg[1]);
        if (slot >= 0)
            setSlotValue (slot, "fmode", (float) fmodeIndex (body.getProperty ("mode", "lowpass").toString()));
        return emptyObject();
    }

    // PUT /tracks/{id}/lfo { shape?, rate?, depth?, destination?, sync? } — only
    // the present fields are updated (track-level LFO base config).
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "lfo")
    {
        const juce::String id = seg[1];
        processor.editProject ([&] (Project& proj)
        {
            for (auto& t : proj.tracks)
                if (t.id == id)
                {
                    if (body.hasProperty ("shape"))
                    {
                        const juce::String sh = body["shape"].toString();
                        t.lfoShape = sh == "triangle" ? LfoShape::Triangle
                                   : sh == "square"   ? LfoShape::Square
                                   : sh == "sawtooth" ? LfoShape::Sawtooth
                                   : sh == "random"   ? LfoShape::Random : LfoShape::Sine;
                    }
                    if (body.hasProperty ("destination"))
                    {
                        const juce::String d = body["destination"].toString();
                        t.lfoDest = d == "volume" ? LfoDest::Volume
                                  : d == "pitch"  ? LfoDest::Pitch : LfoDest::Cutoff;
                    }
                    if (body.hasProperty ("rate"))  t.lfoRate  = (float) juce::jlimit (0.01, 40.0, (double) body["rate"]);
                    if (body.hasProperty ("depth")) t.lfoDepth = (float) juce::jlimit (0.0, 1.0, (double) body["depth"]);
                    if (body.hasProperty ("sync"))  t.lfoSync  = (bool) body["sync"];
                    break;
                }
        });
        return emptyObject();
    }

    // PUT /tracks/{id}/mute
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "mute")
    {
        const juce::String id = seg[1];
        bool muted = false;
        processor.editProject ([&] (Project& proj)
        {
            for (auto& t : proj.tracks)
                if (t.id == id) { t.muted = ! t.muted; muted = t.muted; break; }
        });
        auto* o = new juce::DynamicObject();
        o->setProperty ("muted", muted);
        return juce::var (o);
    }

    // PUT /tracks/{id}/solo
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "solo")
    {
        const juce::String id = seg[1];
        bool solo = false, anySolo = false;
        processor.editProject ([&] (Project& proj)
        {
            for (auto& t : proj.tracks)
                if (t.id == id) { t.solo = ! t.solo; solo = t.solo; break; }
            for (auto& t : proj.tracks)
                if (t.solo) anySolo = true;
        });
        auto* o = new juce::DynamicObject();
        o->setProperty ("solo", solo);
        o->setProperty ("any_solo", anySolo);
        return juce::var (o);
    }

    // PUT /transport/playing { playing } — UI play/stop (internal transport).
    if (method == "PUT" && path == "/transport/playing")
    {
        processor.internalPlaying.store ((bool) body.getProperty ("playing", true), std::memory_order_relaxed);
        return emptyObject();
    }

    // PUT /transport/bpm { bpm } — internal transport tempo (20..300).
    if (method == "PUT" && path == "/transport/bpm")
    {
        const double b = (double) body.getProperty ("bpm", 120.0);
        processor.internalBpm.store (juce::jlimit (20.0, 300.0, b), std::memory_order_relaxed);
        return emptyObject();
    }

    // PUT /project/swing { swing }  → drive the APVTS param (already atomic).
    if (method == "PUT" && path == "/project/swing")
    {
        const double s = body.getProperty ("swing", 0.0);
        if (auto* param = processor.apvts.getParameter ("swing"))
            param->setValueNotifyingHost (juce::jlimit (0.0f, 1.0f, (float) s));
        return emptyObject();
    }

    // GET /library — pack/category/sample tree from ~/SILA/library (msg thread).
    if (method == "GET" && path == "/library")
        return libraryTreeVar (SilaAudioProcessor::libraryRoot());

    // PUT /tracks/{id}/samples  body { samples: [layer...] } — assign sample
    // layers to a track: store them in the snapshot AND rebuild that track's
    // sampler (file I/O on the message thread, RT-safe bank swap).
    if (method == "PUT" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "samples")
    {
        const juce::String id     = seg[1];
        const auto         layers = parseSampleLayers (body.getProperty ("samples", juce::var()));
        int trackIndex = -1;
        processor.editProject ([&] (Project& proj)
        {
            for (int i = 0; i < (int) proj.tracks.size(); ++i)
                if (proj.tracks[(size_t) i].id == id)
                {
                    proj.tracks[(size_t) i].samples = layers;
                    trackIndex = i;
                    break;
                }
        });
        if (trackIndex >= 0)
            processor.assignTrackSamples (trackIndex, layers);
        return emptyObject();
    }

    // GET /tracks/{id}/waveform?points=N — downsampled peaks + the track's
    // current layer start/end, for the sample trimmer. Empty waveform for tracks
    // with no assigned sample file (so the UI hides the panel for the demo kit).
    if (method == "GET" && seg.size() == 3 && seg[0] == "tracks" && seg[2] == "waveform")
    {
        const juce::String id = seg[1];
        int points = 600;
        {
            juce::StringArray qp;
            qp.addTokens (query, "&", "");
            for (const auto& kv : qp)
                if (kv.startsWith ("points="))
                    points = kv.fromFirstOccurrenceOf ("points=", false, false).getIntValue();
        }
        points = juce::jlimit (1, 4000, points);

        auto*  o      = new juce::DynamicObject();
        juce::Array<juce::var> wf;
        double start  = 0.0, end = 1.0;

        auto snap = processor.snapshot();
        if (snap != nullptr)
            for (int i = 0; i < (int) snap->tracks.size(); ++i)
                if (snap->tracks[(size_t) i].id == id)
                {
                    const auto& layers = snap->tracks[(size_t) i].samples;
                    if (! layers.empty())   // trimmer only for assigned sample files
                    {
                        start = layers.front().start;
                        end   = layers.front().end;
                        if (auto bank = processor.samplerSnapshot())
                            if (i < (int) bank->size() && (*bank)[(size_t) i] != nullptr)
                                for (float p : (*bank)[(size_t) i]->computePeaks (points))
                                    wf.add ((double) p);
                    }
                    break;
                }

        o->setProperty ("waveform", wf);
        o->setProperty ("length", wf.size());
        o->setProperty ("start", start);
        o->setProperty ("end", end);
        return juce::var (o);
    }

    // POST /export/digitakt — open the native folder picker + transcode. The
    // dialog is async, so the result returns later via the "export" event; this
    // call just acknowledges the launch.
    if (method == "POST" && path == "/export/digitakt")
    {
        launchDigitaktExport();
        auto* o = new juce::DynamicObject();
        o->setProperty ("started", true);
        return juce::var (o);
    }

    // GET /projects — list saved project names in ~/SILA/projects.
    if (method == "GET" && path == "/projects")
    {
        auto* o = new juce::DynamicObject();
        juce::Array<juce::var> names;
        const auto dir = SilaAudioProcessor::projectsDir();
        if (dir.isDirectory())
        {
            auto files = dir.findChildFiles (juce::File::findFiles | juce::File::ignoreHiddenFiles, false, "*.json");
            std::sort (files.begin(), files.end(),
                       [] (const juce::File& a, const juce::File& b)
                       { return a.getFileName().compareNatural (b.getFileName()) < 0; });
            for (const auto& f : files)
                names.add (f.getFileNameWithoutExtension());
        }
        o->setProperty ("projects", names);
        return juce::var (o);
    }

    // POST /projects/save { name } — serialize the snapshot to ~/SILA/projects.
    if (method == "POST" && path == "/projects/save")
    {
        const juce::String name = juce::File::createLegalFileName (body.getProperty ("name", "untitled").toString()).trim();
        auto* o = new juce::DynamicObject();
        if (name.isEmpty())
        {
            o->setProperty ("error", "invalid name");
            return juce::var (o);
        }
        if (auto snap = processor.snapshot())
        {
            // File format: { project: <structure>, params: { id: normalised } } so
            // the automatable slot params round-trip alongside ProjectJson.
            auto* root = new juce::DynamicObject();
            root->setProperty ("project", sila::engine::projectToVar (*snap));
            auto* params = new juce::DynamicObject();
            for (auto* p : processor.getParameters())
                if (auto* wid = dynamic_cast<juce::AudioProcessorParameterWithID*> (p))
                    params->setProperty (wid->paramID, (double) p->getValue());
            root->setProperty ("params", juce::var (params));

            const auto dir = SilaAudioProcessor::projectsDir();
            dir.createDirectory();
            dir.getChildFile (name + ".json")
               .replaceWithText (juce::JSON::toString (juce::var (root), false));
            o->setProperty ("saved", name);
        }
        return juce::var (o);
    }

    // POST /projects/load { name } — read a project file + RCU-swap it in. The UI
    // refreshes via the projectEpoch "project" event that loadProject triggers.
    if (method == "POST" && path == "/projects/load")
    {
        const juce::String name = juce::File::createLegalFileName (body.getProperty ("name", juce::String()).toString());
        auto*  o    = new juce::DynamicObject();
        const auto file = SilaAudioProcessor::projectsDir().getChildFile (name + ".json");
        const juce::var root = file.existsAsFile() ? juce::JSON::parse (file.loadFileAsString()) : juce::var();
        // New format wraps { project, params }; old files are a bare project.
        const juce::var projVar = root.getProperty ("project", juce::var());
        const juce::var actual  = projVar.isObject() ? projVar : root;
        if (actual.isObject())
        {
            processor.loadProject (std::make_shared<const Project> (sila::engine::projectFromVar (actual)));
            if (auto* params = root.getProperty ("params", juce::var()).getDynamicObject())
                for (const auto& kv : params->getProperties())
                    if (auto* p = processor.apvts.getParameter (kv.name.toString()))
                        p->setValueNotifyingHost ((float) (double) kv.value);
            o->setProperty ("loaded", name);
        }
        else
            o->setProperty ("error", "not found or invalid");
        return juce::var (o);
    }

    // ── Song Mode (Phase 6) ──────────────────────────────────────────────────
    // All mutations run on the message thread via editProject() (RCU copy-on-
    // write — the audio thread never blocks) and return the fresh song state, so
    // the UI re-renders straight from the response with no extra round-trip.

    // Edit the active song in place (no-op if the project has no songs).
    auto editActiveSong = [this] (auto&& fn)
    {
        processor.editProject ([&] (Project& proj)
        {
            if (proj.songs.empty()) return;
            const int as = juce::jlimit (0, (int) proj.songs.size() - 1, proj.activeSong);
            fn (proj.songs[(size_t) as]);
        });
    };

    // GET /song — the active song + song list + limits for the song-edit grid.
    if (method == "GET" && path == "/song")
        return songStateVar();

    // PUT /song/active { index } — select which song plays / is edited.
    if (method == "PUT" && path == "/song/active")
    {
        const int idx = (int) body.getProperty ("index", 0);
        processor.editProject ([&] (Project& proj)
        {
            if (! proj.songs.empty())
                proj.activeSong = juce::jlimit (0, (int) proj.songs.size() - 1, idx);
        });
        return songStateVar();
    }

    // POST /song/new { name? } — append a new empty song and select it.
    if (method == "POST" && path == "/song/new")
    {
        const juce::String nm = body.getProperty ("name", juce::String()).toString().trim();
        processor.editProject ([&] (Project& proj)
        {
            if ((int) proj.songs.size() >= Project::kMaxSongs) return;
            Song s;
            s.name = nm.isNotEmpty() ? nm : ("Song " + juce::String ((int) proj.songs.size() + 1));
            proj.songs.push_back (std::move (s));
            proj.activeSong = (int) proj.songs.size() - 1;
        });
        return songStateVar();
    }

    // PUT /song/name { name } — rename the active song.
    if (method == "PUT" && path == "/song/name")
    {
        const juce::String nm = body.getProperty ("name", juce::String()).toString().trim();
        if (nm.isNotEmpty())
            editActiveSong ([&] (Song& s) { s.name = nm; });
        return songStateVar();
    }

    // PUT /song/end { end: loop|stop } — the end-behaviour row.
    if (method == "PUT" && path == "/song/end")
    {
        const juce::String e = body.getProperty ("end", "loop").toString();
        editActiveSong ([&] (Song& s) { s.end = e == "stop" ? SongEnd::Stop : SongEnd::Loop; });
        return songStateVar();
    }

    // POST /song/rows { index?, row? } — insert a row (append if index omitted).
    // Auto-creates a first song if the project has none.
    if (method == "POST" && path == "/song/rows")
    {
        processor.editProject ([&] (Project& proj)
        {
            if (proj.songs.empty())
            {
                Song s; s.name = "Song 1";
                proj.songs.push_back (std::move (s));
                proj.activeSong = 0;
            }
            const int as = juce::jlimit (0, (int) proj.songs.size() - 1, proj.activeSong);
            Song& song = proj.songs[(size_t) as];
            if ((int) song.rows.size() >= Song::kMaxRows) return;

            SongRow row = sila::engine::songRowFromVar (body.getProperty ("row", juce::var()));
            const juce::var iv = body.getProperty ("index", juce::var());
            const int at = iv.isVoid() ? (int) song.rows.size()
                                       : juce::jlimit (0, (int) song.rows.size(), (int) iv);
            song.rows.insert (song.rows.begin() + at, row);
        });
        return songStateVar();
    }

    // PUT /song/rows/{index} { label?, pattern_slot?, repeat?, length?, tempo?,
    //   mutes?, mute_toggle? } — partial edit of one row's fields.
    if (method == "PUT" && seg.size() == 3 && seg[0] == "song" && seg[1] == "rows")
    {
        const int idx = seg[2].getIntValue();
        editActiveSong ([&] (Song& s)
        {
            if (idx < 0 || idx >= (int) s.rows.size()) return;
            SongRow& r = s.rows[(size_t) idx];
            if (body.hasProperty ("label"))        r.label       = body["label"].toString();
            if (body.hasProperty ("pattern_slot")) r.patternSlot = juce::jlimit (0, PatternBank::kNumSlots - 1, (int) body["pattern_slot"]);
            if (body.hasProperty ("repeat"))       r.repeat      = juce::jlimit (1, 32,   (int) body["repeat"]);
            if (body.hasProperty ("length"))       r.length      = juce::jlimit (2, 1024, (int) body["length"]);
            if (body.hasProperty ("tempo"))        r.tempo       = (float) (double) body["tempo"];
            if (body.hasProperty ("mutes"))        r.mutes       = (uint8_t) ((int) body["mutes"] & 0xFF);
            if (body.hasProperty ("mute_toggle"))
            {
                const int slot = (int) body["mute_toggle"];
                if (slot >= 0 && slot < 8) r.mutes ^= (uint8_t) (1u << slot);
            }
        });
        return songStateVar();
    }

    // DELETE /song/rows/{index}
    if (method == "DELETE" && seg.size() == 3 && seg[0] == "song" && seg[1] == "rows")
    {
        const int idx = seg[2].getIntValue();
        editActiveSong ([&] (Song& s)
        {
            if (idx >= 0 && idx < (int) s.rows.size())
                s.rows.erase (s.rows.begin() + idx);
        });
        return songStateVar();
    }

    // GET /sequencer/status — current transport status for the initial fetch on
    // boot (live updates after that arrive via the pushed "status" event).
    if (method == "GET" && path == "/sequencer/status")
        return statusVar (processor.transportPlaying.load (std::memory_order_relaxed),
                          processor.currentBpm.load (std::memory_order_relaxed),
                          processor.currentSongSlot.load (std::memory_order_relaxed),
                          processor.currentSongRow.load (std::memory_order_relaxed),
                          processor.currentSongRepeat.load (std::memory_order_relaxed));

    // Unimplemented endpoints: benign empty object (full app.js cutover is Step 2b+).
    return emptyObject();
}

juce::var SilaAudioProcessorEditor::songStateVar() const
{
    auto* o = new juce::DynamicObject();
    auto snap = processor.snapshot();

    juce::Array<juce::var> names;
    int active = -1;
    if (snap != nullptr && ! snap->songs.empty())
    {
        active = juce::jlimit (0, (int) snap->songs.size() - 1, snap->activeSong);
        for (const auto& s : snap->songs) names.add (s.name);
        o->setProperty ("song", sila::engine::songToVar (snap->songs[(size_t) active]));
    }
    else
    {
        o->setProperty ("song", juce::var());   // no song authored yet
    }
    o->setProperty ("songs",       names);
    o->setProperty ("active_song", active);
    // Limits the UI needs to populate dropdowns / clamp inputs.
    o->setProperty ("max_rows",      sila::engine::Song::kMaxRows);
    o->setProperty ("max_songs",     sila::engine::Project::kMaxSongs);
    o->setProperty ("pattern_slots", sila::engine::PatternBank::kNumSlots);
    return juce::var (o);
}

void SilaAudioProcessorEditor::launchDigitaktExport()
{
    const auto chooserFlags = juce::FileBrowserComponent::openMode
                            | juce::FileBrowserComponent::canSelectDirectories;
    fileChooser = std::make_unique<juce::FileChooser> (
        "Choose an export folder for Digitakt WAVs",
        juce::File::getSpecialLocation (juce::File::userDesktopDirectory),
        juce::String());

    fileChooser->launchAsync (chooserFlags, [this] (const juce::FileChooser& fc)
    {
        const juce::File dir = fc.getResult();
        if (dir == juce::File())
            return;   // cancelled

        const auto snap = processor.snapshot();
        if (snap == nullptr)
            return;

        // File I/O + resampling on the message thread (the chooser callback runs
        // here). No audio-thread / RCU interaction — pure offline transcode.
        const auto result = sila::engine::exportForDigitakt (
            *snap, SilaAudioProcessor::libraryRoot(), dir);

        auto* o = new juce::DynamicObject();
        o->setProperty ("summary",  result.summary());
        o->setProperty ("exported", result.exported);
        o->setProperty ("dir",      dir.getFullPathName());
        webView.emitEventIfBrowserIsVisible ("export", juce::var (o));
    });
}

std::optional<juce::WebBrowserComponent::Resource>
SilaAudioProcessorEditor::serveResource (const juce::String& url)
{
    const auto path = (url == "/") ? juce::String ("index.html")
                                   : url.fromFirstOccurrenceOf ("/", false, false);

    auto give = [] (const char* resourceName, juce::String mime)
        -> std::optional<juce::WebBrowserComponent::Resource>
    {
        int size = 0;
        if (const auto* data = BinaryData::getNamedResource (resourceName, size))
        {
            std::vector<std::byte> bytes (static_cast<size_t> (size));
            std::memcpy (bytes.data(), data, static_cast<size_t> (size));
            return juce::WebBrowserComponent::Resource { std::move (bytes), std::move (mime) };
        }
        return std::nullopt;
    };

    if (path == "index.html")
        return give ("index_html", "text/html");
    if (path == "bridge.js")
        return give ("bridge_js", "text/javascript");
    if (path == "js/juce/index.js")
        return give ("index_js", "text/javascript");
    if (path == "js/juce/check_native_interop.js")
        return give ("check_native_interop_js", "text/javascript");

    return std::nullopt;
}
